<?php

declare(strict_types=1);

/*
 * Prints the public API (every class tagged @api) as markdown: signatures only. Used for the 1.0 freeze review and kept
 * in docs/api-surface.md so a change to it shows up in review.   php scripts/api-surface.php > docs/api-surface.md
 */

require __DIR__ . '/../vendor/autoload.php';

$files = new RecursiveIteratorIterator(new RecursiveDirectoryIterator((string) realpath(__DIR__ . '/../src'), FilesystemIterator::SKIP_DOTS));
$classes = [];
foreach ($files as $f) {
    if (!$f->isFile() || $f->getExtension() !== 'php') {
        continue;
    }
    $rel = substr((string) $f->getRealPath(), strlen((string) realpath(__DIR__ . '/../src')) + 1);
    $fqcn = 'RivetCore\\' . str_replace(['/', '.php'], ['\\', ''], $rel);
    if (!class_exists($fqcn) && !interface_exists($fqcn) && !trait_exists($fqcn) && !enum_exists($fqcn)) {
        continue;
    }
    $r = new ReflectionClass($fqcn);
    $doc = (string) $r->getDocComment();
    if (str_contains($doc, '@internal') || !str_contains($doc, '@api')) {
        continue;
    }
    $classes[$fqcn] = $r;
}
ksort($classes);

$type = static fn (?ReflectionType $t): string => $t === null ? '' : ': ' . $t;
echo "# Public API surface (classes tagged `@api`)\n\nGenerated by `scripts/api-surface.php`; do not edit by hand.\n\n";
foreach ($classes as $name => $r) {
    $kind = $r->isInterface() ? 'interface' : ($r->isEnum() ? 'enum' : ($r->isAbstract() ? 'abstract class' : ($r->isFinal() ? 'final class' : 'class')));
    echo "## `$name` ($kind)\n\n";
    foreach ($r->getReflectionConstants() as $c) {
        if ($c->isPublic()) {
            echo "- const `{$c->getName()}`\n";
        }
    }
    foreach ($r->getMethods(ReflectionMethod::IS_PUBLIC) as $m) {
        if ($m->getDeclaringClass()->getName() !== $name || str_starts_with($m->getName(), '__') && $m->getName() !== '__construct') {
            continue;
        }
        $params = array_map(static function (ReflectionParameter $p): string {
            $s = ($p->getType() ? $p->getType() . ' ' : '') . ($p->isVariadic() ? '...' : '') . '$' . $p->getName();
            if ($p->isDefaultValueAvailable()) {
                $d = $p->getDefaultValue();
                $s .= ' = ' . (is_array($d) ? '[]' : var_export($d, true));
            }

            return $s;
        }, $m->getParameters());
        echo '- ' . ($m->isStatic() ? 'static ' : '') . "`{$m->getName()}(" . implode(', ', $params) . ')' . $type($m->getReturnType()) . "`\n";
    }
    echo "\n";
}
