<?php

declare(strict_types=1);

/*
 * Prints docs/webhook-platforms.md (one setup guide per destination preset) from the Destinations catalog, so the docs can
 * never drift from the data the editions render.   php scripts/webhook-guides.php > docs/webhook-platforms.md
 * tests/Unit/WebhookDocsTest.php fails when the committed file is stale.
 */

require __DIR__ . '/../vendor/autoload.php';

use RivetCore\Webhooks\Destinations;

$out = "# Webhook platform guides\n\n"
    . "Generated by `scripts/webhook-guides.php` from the `Destinations` catalog; do not edit by hand. "
    . "For signing, retries and the URL policy see [webhooks.md](webhooks.md).\n\n"
    . "Platform details change; each guide links the vendor documentation, and notes marked \"verify\" are the ones most likely to drift.\n\n";

$labels = Destinations::categoryLabels();
$out .= "## Contents\n\n";
foreach (Destinations::byCategory() as $cat => $items) {
    $out .= '- ' . $labels[$cat] . ': ' . implode(', ', array_map(static fn ($d) => '[' . $d->name . '](#' . $d->id . ')', $items)) . "\n";
}
$out .= "\n";

foreach (Destinations::byCategory() as $cat => $items) {
    $out .= '## ' . $labels[$cat] . "\n\n";
    foreach ($items as $d) {
        $out .= '<a id="' . $d->id . "\"></a>\n### " . $d->name . "\n\n" . $d->description . "\n\n";
        $out .= '- Preset id: `' . $d->id . "`\n";
        $out .= '- Body format: `' . $d->format . '`, method `' . $d->method . "`\n";
        $out .= '- URL: `' . $d->urlHint . "`\n";
        if ($d->urlPattern !== null) {
            $out .= '- Saved URL must match: `' . $d->urlPattern . "`\n";
        }
        $out .= '- Authentication: ' . implode(', ', array_map(static fn ($m) => $m === $d->defaultAuth ? '**' . $m . '**' : $m, $d->authModes))
            . ($d->defaultAuthHeader !== null ? ' (header `' . $d->defaultAuthHeader . '`)' : '') . "\n";
        $out .= '- Vendor docs: ' . (str_starts_with($d->docsUrl, 'http') ? '<' . $d->docsUrl . '>' : '[' . $d->docsUrl . '](' . basename($d->docsUrl) . ')') . "\n\n";
        if ($d->extraFields !== []) {
            $out .= "Extra fields:\n\n";
            foreach ($d->extraFields as $f) {
                $out .= '- `' . $f->name . '` (' . $f->type . ($f->required ? ', required' : ', optional') . '): ' . $f->help . "\n";
            }
            $out .= "\n";
        }
        $out .= "Setup:\n\n";
        foreach ($d->setupSteps as $i => $step) {
            $out .= ($i + 1) . '. ' . $step . "\n";
        }
        $out .= "\nTest from a shell:\n\n```bash\n" . $d->sampleCurl . "\n```\n\n";
        if ($d->notes !== []) {
            $out .= "Things to know:\n\n";
            foreach ($d->notes as $n) {
                $out .= '- ' . $n . "\n";
            }
            $out .= "\n";
        }
        if ($d->verifySnippets !== []) {
            $out .= "Verifying our signature: this platform can check `X-Rivet-Signature-V2`; see the snippets in [webhooks.md](webhooks.md#verifying-a-signature).\n\n";
        } else {
            $out .= "Signature verification: not available on this platform; the URL (or token) is the secret.\n\n";
        }
    }
}

echo rtrim($out) . "\n";
